version: "3.3"
services:
  parser:
    build: ./parser        
    volumes:
      - data_stream:/data:rw    
    networks:
      - vstream_network    
  # localstack:
  #   container_name: "vstream-localstack"
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     - AWS_DEFAULT_REGION=sa-east-1
  #     - AWS_ACCESS_KEY_ID=fakeAccessKeyId
  #     - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
  #     - DEFAULT_REGION=sa-east-1
  #     - DEBUG=${DEBUG-}
  #     - PERSISTENCE=${PERSISTENCE-}
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}      
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - "./volume:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
    container_name: nginx-filestream
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - data_stream:/usr/share/nginx/html/proxy
    networks:
      - vstream_network

  proxy:
    build: ./proxy
    ports:
      - "8888:5000"
    volumes:
      - data_stream:/app/uploaded:rw    
    networks:
      - vstream_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - vstream_network

  database:
    container_name: vstream_database
    image: postgres
    environment:
      POSTGRES_DB: vstream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - vstream_network    
    volumes:
      - ./proxy/Migrations/create_media_table.sql:/docker-entrypoint-initdb.d/create_media_table.sql
      - ./proxy/Migrations/create_course_table.sql:/docker-entrypoint-initdb.d/create_course_table.sql
    
volumes:
  data_stream:
    name: "vstream_data"

networks:
  vstream_network:
    name: vstream_network    